### ISSUE TITLE
Problem when value is not in the domain of the function

### ISSUE THREAD

**Issue by ghost** [BlackEdder/ggplotd#11]
Code:
auto f = (double x) { return sqrt(pow(x, 2) - 1); };
auto xs = iota(-5, 5, 0.1).array;
auto ysfit = xs.map!((x) => f(x)).array;
auto gg = GGPlotD().put( geomLine( Aes!(typeof(xs), "x", typeof(ysfit), "y")( xs, ysfit ) ) );
gg.put(xaxisRange(-5, 5));
gg.put(yaxisRange(-5, 5));
gg.save("ggplotd.png", 500, 300);

Expected: http://d.darktech.org/fx.png
Output: http://d.darktech.org/ggplotd.png
Domain: x <= -1, x >= 1
http://www.wolframalpha.com/input/?i=sqrt(pow(x,+2)+-+1)

**Comment by BlackEdder** [comment]
Thanks for reporting this. Cairo indeed doesn't deal with nan values very well. I guess it will make sense for [NumericLabel](https://github.com/BlackEdder/ggplotd/blob/master/source/ggplotd/aes.d#L594) to ignore NaN values passed to it.

**Comment by BlackEdder** [comment]
That didn't work out, because discarding invalid values for y does not discard values for x. Will probably end up fixing it more low level. Note on what needs to be done:
- [ ] Everywhere where we call cairo.Context check that values are actually valid before plotting (3 or four places)
- [ ] Check that bounds.adapt ignores NaN values

It might take me a couple of days before I have time to do that though.

Temporary work around would be:

``` D
 geomLine( Aes!(typeof(xs), "x", typeof(ysfit), "y")( xs, ysfit ).filter!((crds) => !isNaN(crds.y)) )
```

**Comment by BlackEdder** [comment]
Working on this in PR #12

**Comment by ghost** [comment]
Thank you BlackEdder. Just want to let you know http://calc.darktech.org/ is using ggplotd as plot engine; both axes currently fixed at -5, 5 (good enough for my calculus classes).

**Comment by BlackEdder** [comment]
Thanks for letting me know, that looks interesting.

**Comment by BlackEdder** [comment]
FYI I did add a stateFunction to ggplotd that might be useful for you. If you have any suggestions on the design please let me know. 
http://blackedder.github.io/ggplotd/stat.html

**Comment by ghost** [comment]
Thank you. I will try statFunction.
